# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EO18_2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'MapboxNavigation', '~> 0.19.1'

  # Pods for EO18_2

  target 'EO18_2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EO18_2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
