# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'EO18_3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'MapboxSceneKit', :git => 'https://github.com/mapbox/mapbox-scenekit.git'
 pod 'MapboxMobileEvents'
  # Pods for EO18_3

  target 'EO18_3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EO18_3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
